version: '3.9'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: ansdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: