version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: frontend_vue
    ports:
      - "3000:3000"
    depends_on:
      - backend
