\copy operadoras_ativas(registro_ans, cnpj, razao_social, nome_fantasia, modalidade, logradouro, numero, complemento, bairro, cidade, uf, cep, ddd, telefone, fax, email, representante, cargo_representante, regiao_comercializacao, data_registro) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/Relatorio_cadop.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';

\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/1T2023.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/2t2023.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/3T2023.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/4T2023.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/1T2024.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/2T2024.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/3T2024.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';
\copy demonstracoes_contabeis(data, registro_ans, codigo_conta, descricao, saldo_inicial, saldo_final) FROM '/mnt/c/Users/rajin/OneDrive/Área de Trabalho/TesteNivelamento/TesteNivelamento/TesteNivelamento_Felipe/downloads/demonstracoes_contabeis/4T2024.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN1';

ALTER TABLE demonstracoes_contabeis ALTER COLUMN saldo_inicial TYPE NUMERIC(20, 2) USING REPLACE(saldo_inicial, ',', '.')::numeric;
ALTER TABLE demonstracoes_contabeis ALTER COLUMN saldo_final TYPE NUMERIC(20, 2) USING REPLACE(saldo_final, ',', '.')::numeric;
